Sana = input("Anna sana: ")
print("Antamasi sanan kolme ensimmäistä kirjainta ovat", Sana[0:3])
print("Sanan neljä viimeistä kirjainta ovat", Sana[len(Sana)-4:len(Sana)])
print("Kirjaimet 3, 4, 5 ja 6 ovat", Sana[2:6])
print()
print("Sanan joka kolmas kirjain alkaen ensimmäisestä kirjaimesta:", Sana[0::3])
print()
print("Antamasi sana", "'" + Sana + "'", "on takaperin", "'" + Sana[::-1] + "'.")
print()
Aloitus = int(input("Anna aloituspaikka: "))
Lopetus = int(input("Anna lopetuspaikka: "))
Siirtyma = int(input("Anna siirtymä: "))
print("Antamillasi asetuksilla sana", Sana, "tulostuu näin:", Sana[Aloitus:Lopetus:Siirtyma])
print()
print("Antamasi sanan pituus oli", len(Sana), "merkkiä.")
print("Kiitos ohjelman käytöstä.")
